spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    expired-time-ms: ${TOKEN_EXPIRED_TIME_MS}


#project:
#  upload:
#    path: C:\Users\Playdata\IdeaProjects\ex\demo\src\main\resources\static\images


cloud:
  aws:
    s3:
      bucket: ehdtjq2024-s3
    credentials:
      access-key: AKIAY7J2K4VR5DDNRXTJ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

